x-app-common: &app-common
  build:
    context: .
    dockerfile: Dockerfile
    args:
      ENVIRONMENT: ${ENVIRONMENT:-live}
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
      NEXT_PUBLIC_API_TIMEOUT: ${NEXT_PUBLIC_API_TIMEOUT:-120000}
      NEXT_PUBLIC_NOTIFICATIONS_REFETCH_INTERVAL: ${NEXT_PUBLIC_NOTIFICATIONS_REFETCH_INTERVAL:-1800000}
      NEXT_PUBLIC_PROFILE_REFRESH_INTERVAL: ${NEXT_PUBLIC_PROFILE_REFRESH_INTERVAL:-1800000}
      NEXT_PUBLIC_SANITY_DATASET: ${NEXT_PUBLIC_SANITY_DATASET}
      NEXT_PUBLIC_SANITY_PROJECT_ID: ${NEXT_PUBLIC_SANITY_PROJECT_ID}
      NEXT_PUBLIC_CLOUDFLARE_SITE_KEY: ${NEXT_PUBLIC_CLOUDFLARE_SITE_KEY}
      NEXT_PUBLIC_CLOUDFLARE_SECRET_KEY: ${NEXT_PUBLIC_CLOUDFLARE_SECRET_KEY}
  restart: unless-stopped
  environment:
    NODE_ENV: production
    NEXT_TELEMETRY_DISABLED: "1"
    NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    NEXT_PUBLIC_API_TIMEOUT: ${NEXT_PUBLIC_API_TIMEOUT:-120000}
    NEXT_PUBLIC_NOTIFICATIONS_REFETCH_INTERVAL: ${NEXT_PUBLIC_NOTIFICATIONS_REFETCH_INTERVAL:-1800000}
    NEXT_PUBLIC_PROFILE_REFRESH_INTERVAL: ${NEXT_PUBLIC_PROFILE_REFRESH_INTERVAL:-1800000}
    NEXT_PUBLIC_SANITY_DATASET: ${NEXT_PUBLIC_SANITY_DATASET}
    NEXT_PUBLIC_SANITY_PROJECT_ID: ${NEXT_PUBLIC_SANITY_PROJECT_ID}
    SANITY_REVALIDATE_SECRET: ${SANITY_REVALIDATE_SECRET}
    NEXT_PUBLIC_CLOUDFLARE_SITE_KEY: ${NEXT_PUBLIC_CLOUDFLARE_SITE_KEY}
    NEXT_PUBLIC_CLOUDFLARE_SECRET_KEY: ${NEXT_PUBLIC_CLOUDFLARE_SECRET_KEY}

    E2E_ADMIN_USERNAME: ${E2E_ADMIN_USERNAME}
    E2E_ADMIN_PASSWORD: ${E2E_ADMIN_PASSWORD}
    E2E_BRAND_USERNAME: ${E2E_BRAND_USERNAME}
    E2E_BRAND_PASSWORD: ${E2E_BRAND_PASSWORD}
    E2E_CREATOR_USERNAME: ${E2E_CREATOR_USERNAME}
    E2E_CREATOR_PASSWORD: ${E2E_CREATOR_PASSWORD}

services:
  app_blue:
    <<: *app-common
    container_name: ${DEPLOY_APP_NAME:-huerray-web}-blue
    ports:
      - "${BLUE_PORT:-18080}:8080"

  app_green:
    <<: *app-common
    container_name: ${DEPLOY_APP_NAME:-huerray-web}-green
    ports:
      - "${GREEN_PORT:-28080}:8080"
