import { UtilsCampaignCategory } from '@/lib/api/generated';
import { ModelCampaign } from './types';

export const campaigns: ModelCampaign[] = [
  {
    campaign_id: '1',
    brand_id: '1',
    campaign_name: 'Summer Collection Launch',
    description:
      'Showcase our new summer fashion line with vibrant, energetic content',
    campaign_status: 'running',
    number_of_creators_wanted: 12,
    number_of_videos_wanted: 24,
    brand_name: 'Acme Fashion',
    category: 'fashion',
    content_type: 'video',
    brand_logo: 'https://api.dicebear.com/7.x/initials/svg?seed=Summer',
    video_format: 'mp4',
    video_duration_in_seconds: 30,
    created_at: '2024-06-01T00:00:00Z',
    updated_at: '2024-12-15T00:00:00Z',
    brand_accepted: true,
    applications: [
      {
        first_name: 'Emma',
        last_name: 'Wilson',
        email: 'emma.wilson@example.com',
        username: '@emma',
        avatar: 'https://i.pravatar.cc/150?img=1',
      },
      {
        first_name: 'James',
        last_name: 'Anderson',
        email: 'james.anderson@example.com',
        username: '@james',
        avatar: 'https://i.pravatar.cc/150?img=2',
      },
      {
        first_name: 'Sophia',
        last_name: 'Martinez',
        email: 'sophia.martinez@example.com',
        username: '@sophia',
        avatar: 'https://i.pravatar.cc/150?img=3',
      },
      {
        first_name: 'Oliver',
        last_name: 'Taylor',
        email: 'oliver.taylor@example.com',
        username: '@oliver',
        avatar: 'https://i.pravatar.cc/150?img=4',
      },
      {
        first_name: 'Ava',
        last_name: 'Thomas',
        email: 'ava.thomas@example.com',
        username: '@ava',
        avatar: 'https://i.pravatar.cc/150?img=5',
      },
    ],
    creators: [
      {
        first_name: 'Emma',
        last_name: 'Wilson',
        email: 'emma.wilson@example.com',
        username: '@emma',
        avatar: 'https://i.pravatar.cc/150?img=1',
      },
      {
        first_name: 'James',
        last_name: 'Anderson',
        email: 'james.anderson@example.com',
        username: '@james',
        avatar: 'https://i.pravatar.cc/150?img=2',
      },
      {
        first_name: 'Sophia',
        last_name: 'Martinez',
        email: 'sophia.martinez@example.com',
        username: '@sophia',
        avatar: 'https://i.pravatar.cc/150?img=3',
      },
    ],
    product_image_url: 'https://via.placeholder.com/150',
    product_url: 'https://via.placeholder.com/150',
  },
  {
    campaign_id: '2',
    campaign_name: 'Back to School Campaign',
    description:
      'Educational content featuring study tips and productivity hacks',
    campaign_status: 'running',
    number_of_creators_wanted: 8,
    number_of_videos_wanted: 16,
    category: 'education',
    content_type: 'video',
    video_format: 'mp4',
    video_duration_in_seconds: 60,
    created_at: '2024-08-15T00:00:00Z',
    updated_at: '2024-12-10T00:00:00Z',
    brand_accepted: true,
    applications: [
      {
        first_name: 'Liam',
        last_name: 'Garcia',
        avatar: 'https://i.pravatar.cc/150?img=6',
      },
      {
        first_name: 'Isabella',
        last_name: 'Rodriguez',
        avatar: 'https://i.pravatar.cc/150?img=7',
      },
      {
        first_name: 'Noah',
        last_name: 'Hernandez',
        avatar: 'https://i.pravatar.cc/150?img=8',
      },
    ],
    creators: [
      {
        first_name: 'Liam',
        last_name: 'Garcia',
        avatar: 'https://i.pravatar.cc/150?img=6',
      },
      {
        first_name: 'Isabella',
        last_name: 'Rodriguez',
        avatar: 'https://i.pravatar.cc/150?img=7',
      },
    ],
    product_image_url: 'https://via.placeholder.com/150',
    product_url: 'https://via.placeholder.com/150',
  },
  {
    campaign_id: '3',
    campaign_name: 'Holiday Sale Promo',
    description: 'Create excitement around our biggest sale of the year',
    campaign_status: 'created',
    number_of_creators_wanted: 15,
    number_of_videos_wanted: 30,
    category: 'other',
    content_type: 'video',
    video_format: 'mp4',
    video_duration_in_seconds: 45,
    created_at: '2024-11-15T00:00:00Z',
    updated_at: '2024-11-15T00:00:00Z',
    brand_accepted: false,
    applications: [],
    creators: [],
    product_image_url: 'https://via.placeholder.com/150',
    product_url: 'https://via.placeholder.com/150',
  },
  {
    campaign_id: '4',
    campaign_name: 'Spring Refresh',
    description: 'Beauty and wellness content for the spring season',
    campaign_status: 'completed',
    number_of_creators_wanted: 15,
    number_of_videos_wanted: 30,
    category: 'beauty',
    content_type: 'video',
    video_format: 'mp4',
    video_duration_in_seconds: 30,
    created_at: '2024-03-01T00:00:00Z',
    updated_at: '2024-05-31T00:00:00Z',
    brand_accepted: true,
    applications: [
      {
        first_name: 'Mia',
        last_name: 'Lopez',
        avatar: 'https://i.pravatar.cc/150?img=9',
      },
      {
        first_name: 'Elijah',
        last_name: 'Gonzalez',
        avatar: 'https://i.pravatar.cc/150?img=10',
      },
      {
        first_name: 'Charlotte',
        last_name: 'Perez',
        avatar: 'https://i.pravatar.cc/150?img=11',
      },
      {
        first_name: 'William',
        last_name: 'Sanchez',
        avatar: 'https://i.pravatar.cc/150?img=12',
      },
    ],
    creators: [
      {
        first_name: 'Mia',
        last_name: 'Lopez',
        avatar: 'https://i.pravatar.cc/150?img=9',
      },
      {
        first_name: 'Elijah',
        last_name: 'Gonzalez',
        avatar: 'https://i.pravatar.cc/150?img=10',
      },
    ],
    product_image_url: 'https://via.placeholder.com/150',
    product_url: 'https://via.placeholder.com/150',
  },
  {
    campaign_id: '5',
    campaign_name: 'Fitness Challenge 2024',
    description:
      'Motivational fitness content showcasing workout routines and healthy lifestyle',
    campaign_status: 'running',
    number_of_creators_wanted: 10,
    number_of_videos_wanted: 20,
    category: UtilsCampaignCategory.CampaignCategoryHealthFood,
    content_type: 'video',
    video_format: 'mp4',
    video_duration_in_seconds: 45,
    created_at: '2024-01-10T00:00:00Z',
    updated_at: '2024-12-18T00:00:00Z',
    brand_accepted: true,
    applications: [
      {
        first_name: 'Amelia',
        last_name: 'Rivera',
        avatar: 'https://i.pravatar.cc/150?img=13',
      },
      {
        first_name: 'Benjamin',
        last_name: 'Torres',
        avatar: 'https://i.pravatar.cc/150?img=14',
      },
      {
        first_name: 'Harper',
        last_name: 'Flores',
        avatar: 'https://i.pravatar.cc/150?img=15',
      },
      {
        first_name: 'Lucas',
        last_name: 'Ramirez',
        avatar: 'https://i.pravatar.cc/150?img=16',
      },
      {
        first_name: 'Evelyn',
        last_name: 'Cruz',
        avatar: 'https://i.pravatar.cc/150?img=17',
      },
      {
        first_name: 'Henry',
        last_name: 'Morales',
        avatar: 'https://i.pravatar.cc/150?img=18',
      },
    ],
    creators: [
      {
        first_name: 'Amelia',
        last_name: 'Rivera',
        avatar: 'https://i.pravatar.cc/150?img=13',
      },
      {
        first_name: 'Benjamin',
        last_name: 'Torres',
        avatar: 'https://i.pravatar.cc/150?img=14',
      },
      {
        first_name: 'Harper',
        last_name: 'Flores',
        avatar: 'https://i.pravatar.cc/150?img=15',
      },
      {
        first_name: 'Lucas',
        last_name: 'Ramirez',
        avatar: 'https://i.pravatar.cc/150?img=16',
      },
    ],
    product_image_url: 'https://via.placeholder.com/150',
    product_url: 'https://via.placeholder.com/150',
  },
  {
    campaign_id: '6',
    campaign_name: 'Tech Gadget Reviews',
    description: 'Authentic reviews and unboxing of our latest tech products',
    campaign_status: 'running',
    number_of_creators_wanted: 6,
    number_of_videos_wanted: 12,
    category: UtilsCampaignCategory.CampaignCategoryAppliances,
    content_type: 'video',
    video_format: 'mp4',
    video_duration_in_seconds: 90,
    created_at: '2024-09-01T00:00:00Z',
    updated_at: '2024-12-17T00:00:00Z',
    brand_accepted: true,
    applications: [
      {
        first_name: 'Alexander',
        last_name: 'Ortiz',
        avatar: 'https://i.pravatar.cc/150?img=19',
      },
      {
        first_name: 'Ella',
        last_name: 'Reyes',
        avatar: 'https://i.pravatar.cc/150?img=20',
      },
      {
        first_name: 'Sebastian',
        last_name: 'Gutierrez',
        avatar: 'https://i.pravatar.cc/150?img=21',
      },
      {
        first_name: 'Avery',
        last_name: 'Jimenez',
        avatar: 'https://i.pravatar.cc/150?img=22',
      },
    ],
    creators: [
      {
        first_name: 'Alexander',
        last_name: 'Ortiz',
        avatar: 'https://i.pravatar.cc/150?img=19',
      },
      {
        first_name: 'Ella',
        last_name: 'Reyes',
        avatar: 'https://i.pravatar.cc/150?img=20',
      },
    ],
    product_image_url: 'https://via.placeholder.com/150',
    product_url: 'https://via.placeholder.com/150',
  },
  {
    campaign_id: '7',
    campaign_name: 'Eco-Friendly Living',
    description:
      'Sustainable lifestyle content promoting our eco-friendly products',
    campaign_status: 'pending_approval',
    number_of_creators_wanted: 8,
    number_of_videos_wanted: 16,
    category: UtilsCampaignCategory.CampaignCategoryAppliances,
    content_type: 'video',
    video_format: 'mp4',
    video_duration_in_seconds: 60,
    created_at: '2024-10-20T00:00:00Z',
    updated_at: '2024-12-05T00:00:00Z',
    brand_accepted: false,
    applications: [
      {
        first_name: 'Scarlett',
        last_name: 'Mendoza',
        avatar: 'https://i.pravatar.cc/150?img=23',
      },
      {
        first_name: 'Jackson',
        last_name: 'Vargas',
        avatar: 'https://i.pravatar.cc/150?img=24',
      },
    ],
    creators: [],
    product_image_url: 'https://via.placeholder.com/150',
    product_url: 'https://via.placeholder.com/150',
  },
  {
    campaign_id: '8',
    campaign_name: 'Gaming Highlights',
    description: 'Gaming content featuring our sponsored games and accessories',
    campaign_status: 'running',
    number_of_creators_wanted: 20,
    number_of_videos_wanted: 40,
    category: 'gaming',
    content_type: 'video',
    video_format: 'mp4',
    video_duration_in_seconds: 120,
    created_at: '2024-07-15T00:00:00Z',
    updated_at: '2024-12-16T00:00:00Z',
    brand_accepted: true,
    applications: [
      {
        first_name: 'Victoria',
        last_name: 'Castro',
        avatar: 'https://i.pravatar.cc/150?img=25',
      },
      {
        first_name: 'Daniel',
        last_name: 'Ruiz',
        avatar: 'https://i.pravatar.cc/150?img=26',
      },
      {
        first_name: 'Luna',
        last_name: 'Alvarez',
        avatar: 'https://i.pravatar.cc/150?img=27',
      },
      {
        first_name: 'Matthew',
        last_name: 'Romero',
        avatar: 'https://i.pravatar.cc/150?img=28',
      },
      {
        first_name: 'Grace',
        last_name: 'Diaz',
        avatar: 'https://i.pravatar.cc/150?img=29',
      },
      {
        first_name: 'David',
        last_name: 'Aguilar',
        avatar: 'https://i.pravatar.cc/150?img=30',
      },
      {
        first_name: 'Chloe',
        last_name: 'Medina',
        avatar: 'https://i.pravatar.cc/150?img=31',
      },
      {
        first_name: 'Joseph',
        last_name: 'Navarro',
        avatar: 'https://i.pravatar.cc/150?img=32',
      },
    ],
    creators: [
      {
        first_name: 'Victoria',
        last_name: 'Castro',
        avatar: 'https://i.pravatar.cc/150?img=25',
      },
      {
        first_name: 'Daniel',
        last_name: 'Ruiz',
        avatar: 'https://i.pravatar.cc/150?img=26',
      },
      {
        first_name: 'Luna',
        last_name: 'Alvarez',
        avatar: 'https://i.pravatar.cc/150?img=27',
      },
      {
        first_name: 'Matthew',
        last_name: 'Romero',
        avatar: 'https://i.pravatar.cc/150?img=28',
      },
      {
        first_name: 'Grace',
        last_name: 'Diaz',
        avatar: 'https://i.pravatar.cc/150?img=29',
      },
    ],
    product_image_url: 'https://via.placeholder.com/150',
    product_url: 'https://via.placeholder.com/150',
  },
  {
    campaign_id: '9',
    campaign_name: 'Food & Recipe Series',
    description: 'Delicious recipe content featuring our kitchen products',
    campaign_status: 'completed',
    number_of_creators_wanted: 5,
    number_of_videos_wanted: 10,
    category: 'food',
    content_type: 'video',
    video_format: 'mp4',
    video_duration_in_seconds: 60,
    created_at: '2024-04-01T00:00:00Z',
    updated_at: '2024-06-30T00:00:00Z',
    brand_accepted: true,
    applications: [
      {
        first_name: 'Zoey',
        last_name: 'Nunez',
        avatar: 'https://i.pravatar.cc/150?img=33',
      },
      {
        first_name: 'Samuel',
        last_name: 'Ramos',
        avatar: 'https://i.pravatar.cc/150?img=34',
      },
      {
        first_name: 'Lillian',
        last_name: 'Ortega',
        avatar: 'https://i.pravatar.cc/150?img=35',
      },
    ],
    creators: [
      {
        first_name: 'Zoey',
        last_name: 'Nunez',
        avatar: 'https://i.pravatar.cc/150?img=33',
      },
      {
        first_name: 'Samuel',
        last_name: 'Ramos',
        avatar: 'https://i.pravatar.cc/150?img=34',
      },
    ],
    product_image_url: 'https://via.placeholder.com/150',
    product_url: 'https://via.placeholder.com/150',
  },
  {
    campaign_id: '10',
    campaign_name: 'Travel Adventures',
    description: 'Travel vlogs showcasing destinations and our travel gear',
    campaign_status: 'running',
    number_of_creators_wanted: 12,
    number_of_videos_wanted: 24,
    category: 'travel',
    content_type: 'video',
    video_format: 'mp4',
    video_duration_in_seconds: 90,
    created_at: '2024-05-10T00:00:00Z',
    updated_at: '2024-12-12T00:00:00Z',
    brand_accepted: true,
    applications: [
      {
        first_name: 'Penelope',
        last_name: 'Silva',
        avatar: 'https://i.pravatar.cc/150?img=36',
      },
      {
        first_name: 'Jack',
        last_name: 'Herrera',
        avatar: 'https://i.pravatar.cc/150?img=37',
      },
      {
        first_name: 'Aria',
        last_name: 'Vazquez',
        avatar: 'https://i.pravatar.cc/150?img=38',
      },
      {
        first_name: 'Owen',
        last_name: 'Castillo',
        avatar: 'https://i.pravatar.cc/150?img=39',
      },
      {
        first_name: 'Riley',
        last_name: 'Santos',
        avatar: 'https://i.pravatar.cc/150?img=40',
      },
    ],
    creators: [
      {
        first_name: 'Penelope',
        last_name: 'Silva',
        avatar: 'https://i.pravatar.cc/150?img=36',
      },
      {
        first_name: 'Jack',
        last_name: 'Herrera',
        avatar: 'https://i.pravatar.cc/150?img=37',
      },
      {
        first_name: 'Aria',
        last_name: 'Vazquez',
        avatar: 'https://i.pravatar.cc/150?img=38',
      },
    ],
    product_image_url: 'https://via.placeholder.com/150',
    product_url: 'https://via.placeholder.com/150',
  },
  {
    campaign_id: '11',
    campaign_name: 'Pet Care Tips',
    description: 'Pet care and training content featuring our pet products',
    campaign_status: 'created',
    number_of_creators_wanted: 7,
    number_of_videos_wanted: 14,
    category: 'pets',
    content_type: 'video',
    video_format: 'mp4',
    video_duration_in_seconds: 45,
    created_at: '2024-11-01T00:00:00Z',
    updated_at: '2024-11-01T00:00:00Z',
    brand_accepted: false,
    applications: [
      {
        first_name: 'Layla',
        last_name: 'Pena',
        avatar: 'https://i.pravatar.cc/150?img=41',
      },
      {
        first_name: 'Carter',
        last_name: 'Fernandez',
        avatar: 'https://i.pravatar.cc/150?img=42',
      },
    ],
    creators: [],
    product_image_url: 'https://via.placeholder.com/150',
    product_url: 'https://via.placeholder.com/150',
  },
  {
    campaign_id: '12',
    campaign_name: 'DIY Home Decor',
    description: 'Creative DIY content for home decoration and organization',
    campaign_status: 'running',
    number_of_creators_wanted: 9,
    number_of_videos_wanted: 18,
    category: 'home',
    content_type: 'video',
    video_format: 'mp4',
    video_duration_in_seconds: 75,
    created_at: '2024-08-01T00:00:00Z',
    updated_at: '2024-12-14T00:00:00Z',
    brand_accepted: true,
    applications: [
      {
        first_name: 'Nora',
        last_name: 'Mendez',
        avatar: 'https://i.pravatar.cc/150?img=43',
      },
      {
        first_name: 'Wyatt',
        last_name: 'Moreno',
        avatar: 'https://i.pravatar.cc/150?img=44',
      },
      {
        first_name: 'Hannah',
        last_name: 'Campos',
        avatar: 'https://i.pravatar.cc/150?img=45',
      },
      {
        first_name: 'Julian',
        last_name: 'Delgado',
        avatar: 'https://i.pravatar.cc/150?img=46',
      },
    ],
    creators: [
      {
        first_name: 'Nora',
        last_name: 'Mendez',
        avatar: 'https://i.pravatar.cc/150?img=43',
      },
      {
        first_name: 'Wyatt',
        last_name: 'Moreno',
        avatar: 'https://i.pravatar.cc/150?img=44',
      },
      {
        first_name: 'Hannah',
        last_name: 'Campos',
        avatar: 'https://i.pravatar.cc/150?img=45',
      },
    ],
    product_image_url: 'https://via.placeholder.com/150',
    product_url: 'https://via.placeholder.com/150',
  },
  {
    campaign_id: '13',
    campaign_name: 'Summer Music Festival',
    description:
      'Promote our upcoming music festival with energetic and fun content.',
    campaign_status: 'running',
    number_of_creators_wanted: 20,
    number_of_videos_wanted: 40,
    category: 'entertainment',
    content_type: 'video',
    video_format: 'mp4',
    video_duration_in_seconds: 45,
    created_at: '2024-05-20T00:00:00Z',
    updated_at: '2024-12-19T00:00:00Z',
    brand_accepted: true,
    applications: [
      {
        first_name: 'Leo',
        last_name: 'King',
        avatar: 'https://i.pravatar.cc/150?img=47',
      },
      {
        first_name: 'Mila',
        last_name: 'Scott',
        avatar: 'https://i.pravatar.cc/150?img=48',
      },
    ],
    creators: [
      {
        first_name: 'Leo',
        last_name: 'King',
        avatar: 'https://i.pravatar.cc/150?img=47',
      },
    ],
    product_image_url: 'https://via.placeholder.com/150',
    product_url: 'https://via.placeholder.com/150',
  },
  {
    campaign_id: '14',
    campaign_name: 'Mental Health Awareness',
    description: 'Share personal stories and tips for mental well-being.',
    campaign_status: 'created',
    number_of_creators_wanted: 10,
    number_of_videos_wanted: 10,
    category: UtilsCampaignCategory.CampaignCategoryHealthFood,
    content_type: 'video',
    video_format: 'mp4',
    video_duration_in_seconds: 60,
    created_at: '2024-11-25T00:00:00Z',
    updated_at: '2024-11-25T00:00:00Z',
    brand_accepted: false,
    applications: [],
    creators: [],
    product_image_url: 'https://via.placeholder.com/150',
    product_url: 'https://via.placeholder.com/150',
  },
  {
    campaign_id: '15',
    campaign_name: 'Gourmet Coffee Experience',
    description: 'Review our premium coffee blends and brewing equipment.',
    campaign_status: 'running',
    number_of_creators_wanted: 8,
    number_of_videos_wanted: 16,
    category: 'food',
    content_type: 'video',
    video_format: 'mp4',
    video_duration_in_seconds: 30,
    created_at: '2024-09-15T00:00:00Z',
    updated_at: '2024-12-18T00:00:00Z',
    brand_accepted: true,
    applications: [
      {
        first_name: 'Ezra',
        last_name: 'Baker',
        avatar: 'https://i.pravatar.cc/150?img=49',
      },
      {
        first_name: 'Aurora',
        last_name: 'Adams',
        avatar: 'https://i.pravatar.cc/150?img=50',
      },
      {
        first_name: 'Thomas',
        last_name: 'Nelson',
        avatar: 'https://i.pravatar.cc/150?img=51',
      },
    ],
    creators: [
      {
        first_name: 'Ezra',
        last_name: 'Baker',
        avatar: 'https://i.pravatar.cc/150?img=49',
      },
      {
        first_name: 'Aurora',
        last_name: 'Adams',
        avatar: 'https://i.pravatar.cc/150?img=50',
      },
    ],
    product_image_url: 'https://via.placeholder.com/150',
    product_url: 'https://via.placeholder.com/150',
  },
  {
    campaign_id: '16',
    campaign_name: 'Winter Fashion Trends',
    description: 'Highlight the cozy and stylish winter collection.',
    campaign_status: 'pending_approval',
    number_of_creators_wanted: 15,
    number_of_videos_wanted: 30,
    category: 'fashion',
    content_type: 'video',
    video_format: 'mp4',
    video_duration_in_seconds: 45,
    created_at: '2024-10-10T00:00:00Z',
    updated_at: '2024-11-05T00:00:00Z',
    brand_accepted: false,
    applications: [
      {
        first_name: 'Eliana',
        last_name: 'Carter',
        avatar: 'https://i.pravatar.cc/150?img=52',
      },
    ],
    creators: [],
    product_image_url: 'https://via.placeholder.com/150',
    product_url: 'https://via.placeholder.com/150',
  },
  {
    campaign_id: '17',
    campaign_name: 'Smart Home Devices',
    description: 'Demonstrate how our smart home devices make life easier.',
    campaign_status: 'completed',
    number_of_creators_wanted: 5,
    number_of_videos_wanted: 10,
    category: UtilsCampaignCategory.CampaignCategorySoftware,
    content_type: 'video',
    video_format: 'mp4',
    video_duration_in_seconds: 90,
    created_at: '2024-02-15T00:00:00Z',
    updated_at: '2024-05-20T00:00:00Z',
    brand_accepted: true,
    applications: [
      {
        first_name: 'Aaron',
        last_name: 'Mitchell',
        avatar: 'https://i.pravatar.cc/150?img=53',
      },
      {
        first_name: 'Violet',
        last_name: 'Perez',
        avatar: 'https://i.pravatar.cc/150?img=54',
      },
    ],
    creators: [
      {
        first_name: 'Aaron',
        last_name: 'Mitchell',
        avatar: 'https://i.pravatar.cc/150?img=53',
      },
      {
        first_name: 'Violet',
        last_name: 'Perez',
        avatar: 'https://i.pravatar.cc/150?img=54',
      },
    ],
    product_image_url: 'https://via.placeholder.com/150',
    product_url: 'https://via.placeholder.com/150',
  },
  {
    campaign_id: '18',
    campaign_name: 'Yoga for Beginners',
    description: 'Simple yoga routines using our mats and apparel.',
    campaign_status: 'running',
    number_of_creators_wanted: 10,
    number_of_videos_wanted: 20,
    category: UtilsCampaignCategory.CampaignCategoryHealthFood,
    content_type: 'video',
    video_format: 'mp4',
    video_duration_in_seconds: 60,
    created_at: '2024-06-05T00:00:00Z',
    updated_at: '2024-12-19T00:00:00Z',
    brand_accepted: true,
    applications: [
      {
        first_name: 'Adrian',
        last_name: 'Roberts',
        avatar: 'https://i.pravatar.cc/150?img=55',
      },
      {
        first_name: 'Hazel',
        last_name: 'Turner',
        avatar: 'https://i.pravatar.cc/150?img=56',
      },
      {
        first_name: 'Cameron',
        last_name: 'Phillips',
        avatar: 'https://i.pravatar.cc/150?img=57',
      },
    ],
    creators: [
      {
        first_name: 'Adrian',
        last_name: 'Roberts',
        avatar: 'https://i.pravatar.cc/150?img=55',
      },
      {
        first_name: 'Hazel',
        last_name: 'Turner',
        avatar: 'https://i.pravatar.cc/150?img=56',
      },
    ],
    product_image_url: 'https://via.placeholder.com/150',
    product_url: 'https://via.placeholder.com/150',
  },
  {
    campaign_id: '19',
    campaign_name: 'Kids Toy Unboxing',
    description: 'Fun and engaging unboxing videos of our newest toys.',
    campaign_status: 'created',
    number_of_creators_wanted: 12,
    number_of_videos_wanted: 24,
    category: UtilsCampaignCategory.CampaignCategoryPerfumes,
    content_type: 'video',
    video_format: 'mp4',
    video_duration_in_seconds: 120,
    created_at: '2024-12-01T00:00:00Z',
    updated_at: '2024-12-01T00:00:00Z',
    brand_accepted: false,
    applications: [],
    creators: [],
    product_image_url: 'https://via.placeholder.com/150',
    product_url: 'https://via.placeholder.com/150',
  },
  {
    campaign_id: '20',
    campaign_name: 'Organic Skincare Routine',
    description:
      'Showcase a morning or night routine with our organic products.',
    campaign_status: 'running',
    number_of_creators_wanted: 8,
    number_of_videos_wanted: 16,
    category: 'beauty',
    content_type: 'video',
    video_format: 'mp4',
    video_duration_in_seconds: 45,
    created_at: '2024-07-20T00:00:00Z',
    updated_at: '2024-12-16T00:00:00Z',
    brand_accepted: true,
    applications: [
      {
        first_name: 'Nathan',
        last_name: 'Campbell',
        avatar: 'https://i.pravatar.cc/150?img=58',
      },
      {
        first_name: 'Stella',
        last_name: 'Parker',
        avatar: 'https://i.pravatar.cc/150?img=59',
      },
    ],
    creators: [
      {
        first_name: 'Stella',
        last_name: 'Parker',
        avatar: 'https://i.pravatar.cc/150?img=59',
      },
    ],
    product_image_url: 'https://via.placeholder.com/150',
    product_url: 'https://via.placeholder.com/150',
  },
  {
    campaign_id: '21',
    campaign_name: 'Mountain Biking Adventure',
    description: 'Action-packed videos of mountain biking trails.',
    campaign_status: 'running',
    number_of_creators_wanted: 6,
    number_of_videos_wanted: 12,
    category: 'sports',
    content_type: 'video',
    video_format: 'mp4',
    video_duration_in_seconds: 60,
    created_at: '2024-08-10T00:00:00Z',
    updated_at: '2024-12-15T00:00:00Z',
    brand_accepted: true,
    applications: [
      {
        first_name: 'Elias',
        last_name: 'Evans',
        avatar: 'https://i.pravatar.cc/150?img=60',
      },
    ],
    creators: [
      {
        first_name: 'Elias',
        last_name: 'Evans',
        avatar: 'https://i.pravatar.cc/150?img=60',
      },
    ],
    product_image_url: 'https://via.placeholder.com/150',
    product_url: 'https://via.placeholder.com/150',
  },
  {
    campaign_id: '22',
    campaign_name: 'Vegan Recipe Challenge',
    description: 'Create a unique vegan dish using our ingredients.',
    campaign_status: 'completed',
    number_of_creators_wanted: 10,
    number_of_videos_wanted: 20,
    category: 'food',
    content_type: 'video',
    video_format: 'mp4',
    video_duration_in_seconds: 60,
    created_at: '2024-03-10T00:00:00Z',
    updated_at: '2024-06-15T00:00:00Z',
    brand_accepted: true,
    applications: [
      {
        first_name: 'Bella',
        last_name: 'Edwards',
        avatar: 'https://i.pravatar.cc/150?img=61',
      },
      {
        first_name: 'Christopher',
        last_name: 'Collins',
        avatar: 'https://i.pravatar.cc/150?img=62',
      },
    ],
    creators: [
      {
        first_name: 'Christopher',
        last_name: 'Collins',
        avatar: 'https://i.pravatar.cc/150?img=62',
      },
    ],
    product_image_url: 'https://via.placeholder.com/150',
    product_url: 'https://via.placeholder.com/150',
  },
  {
    campaign_id: '23',
    campaign_name: 'Language Learning App',
    description: 'Share your progress learning a new language with our app.',
    campaign_status: 'pending_approval',
    number_of_creators_wanted: 15,
    number_of_videos_wanted: 30,
    category: 'education',
    content_type: 'video',
    video_format: 'mp4',
    video_duration_in_seconds: 30,
    created_at: '2024-11-05T00:00:00Z',
    updated_at: '2024-11-20T00:00:00Z',
    brand_accepted: false,
    applications: [],
    creators: [],
    product_image_url: 'https://via.placeholder.com/150',
    product_url: 'https://via.placeholder.com/150',
  },
  {
    campaign_id: '24',
    campaign_name: 'Streetwear Style',
    description: 'Show off your best streetwear looks featuring our brand.',
    campaign_status: 'running',
    number_of_creators_wanted: 20,
    number_of_videos_wanted: 40,
    category: 'fashion',
    content_type: 'video',
    video_format: 'mp4',
    video_duration_in_seconds: 30,
    created_at: '2024-06-25T00:00:00Z',
    updated_at: '2024-12-18T00:00:00Z',
    brand_accepted: true,
    applications: [
      {
        first_name: 'Lucy',
        last_name: 'Stewart',
        avatar: 'https://i.pravatar.cc/150?img=63',
      },
      {
        first_name: 'Maverick',
        last_name: 'Sanchez',
        avatar: 'https://i.pravatar.cc/150?img=64',
      },
      {
        first_name: 'Sophie',
        last_name: 'Morris',
        avatar: 'https://i.pravatar.cc/150?img=65',
      },
    ],
    creators: [
      {
        first_name: 'Lucy',
        last_name: 'Stewart',
        avatar: 'https://i.pravatar.cc/150?img=63',
      },
    ],
    product_image_url: 'https://via.placeholder.com/150',
    product_url: 'https://via.placeholder.com/150',
  },
  {
    campaign_id: '25',
    campaign_name: 'Indie Game Showcase',
    description: 'Gameplay and reviews of our new indie title.',
    campaign_status: 'running',
    number_of_creators_wanted: 10,
    number_of_videos_wanted: 20,
    category: 'gaming',
    content_type: 'video',
    video_format: 'mp4',
    video_duration_in_seconds: 120,
    created_at: '2024-09-05T00:00:00Z',
    updated_at: '2024-12-17T00:00:00Z',
    brand_accepted: true,
    applications: [
      {
        first_name: 'Isaac',
        last_name: 'Rogers',
        avatar: 'https://i.pravatar.cc/150?img=66',
      },
    ],
    creators: [
      {
        first_name: 'Isaac',
        last_name: 'Rogers',
        avatar: 'https://i.pravatar.cc/150?img=66',
      },
    ],
    product_image_url: 'https://via.placeholder.com/150',
    product_url: 'https://via.placeholder.com/150',
  },
  {
    campaign_id: '26',
    campaign_name: 'Digital Art Tools',
    description: 'Demonstrate drawing techniques using our tablet.',
    campaign_status: 'created',
    number_of_creators_wanted: 5,
    number_of_videos_wanted: 10,
    category: UtilsCampaignCategory.CampaignCategoryGaming,
    content_type: 'video',
    video_format: 'mp4',
    video_duration_in_seconds: 60,
    created_at: '2024-12-10T00:00:00Z',
    updated_at: '2024-12-10T00:00:00Z',
    brand_accepted: false,
    applications: [],
    creators: [],
    product_image_url: 'https://via.placeholder.com/150',
    product_url: 'https://via.placeholder.com/150',
  },
  {
    campaign_id: '27',
    campaign_name: 'Sustainable Packaging',
    description: 'Highlight the importance of eco-friendly packaging.',
    campaign_status: 'running',
    number_of_creators_wanted: 8,
    number_of_videos_wanted: 16,
    category: UtilsCampaignCategory.CampaignCategoryBanking,
    content_type: 'video',
    video_format: 'mp4',
    video_duration_in_seconds: 45,
    created_at: '2024-10-01T00:00:00Z',
    updated_at: '2024-12-14T00:00:00Z',
    brand_accepted: true,
    applications: [
      {
        first_name: 'Gabriella',
        last_name: 'Reed',
        avatar: 'https://i.pravatar.cc/150?img=67',
      },
      {
        first_name: 'Anthony',
        last_name: 'Cook',
        avatar: 'https://i.pravatar.cc/150?img=68',
      },
    ],
    creators: [
      {
        first_name: 'Gabriella',
        last_name: 'Reed',
        avatar: 'https://i.pravatar.cc/150?img=67',
      },
    ],
    product_image_url: 'https://via.placeholder.com/150',
    product_url: 'https://via.placeholder.com/150',
  },
  {
    campaign_id: '28',
    campaign_name: 'Book Club Monthly',
    description: 'Reviews and discussions of this months book pick.',
    campaign_status: 'completed',
    number_of_creators_wanted: 12,
    number_of_videos_wanted: 24,
    category: 'education',
    content_type: 'video',
    video_format: 'mp4',
    video_duration_in_seconds: 90,
    created_at: '2024-01-05T00:00:00Z',
    updated_at: '2024-04-10T00:00:00Z',
    brand_accepted: true,
    applications: [
      {
        first_name: 'Lincoln',
        last_name: 'Morgan',
        avatar: 'https://i.pravatar.cc/150?img=69',
      },
    ],
    creators: [
      {
        first_name: 'Lincoln',
        last_name: 'Morgan',
        avatar: 'https://i.pravatar.cc/150?img=69',
      },
    ],
    product_image_url: 'https://via.placeholder.com/150',
    product_url: 'https://via.placeholder.com/150',
  },
  {
    campaign_id: '29',
    campaign_name: 'Mobile Banking App',
    description: 'Show how easy it is to manage finances on the go.',
    campaign_status: 'running',
    number_of_creators_wanted: 15,
    number_of_videos_wanted: 30,
    category: 'finance',
    content_type: 'video',
    video_format: 'mp4',
    video_duration_in_seconds: 45,
    created_at: '2024-07-01T00:00:00Z',
    updated_at: '2024-12-16T00:00:00Z',
    brand_accepted: true,
    applications: [
      {
        first_name: 'Hudson',
        last_name: 'Bell',
        avatar: 'https://i.pravatar.cc/150?img=70',
      },
      {
        first_name: 'Maya',
        last_name: 'Murphy',
        avatar: 'https://i.pravatar.cc/150?img=71',
      },
    ],
    creators: [
      {
        first_name: 'Hudson',
        last_name: 'Bell',
        avatar: 'https://i.pravatar.cc/150?img=70',
      },
    ],
    product_image_url: 'https://via.placeholder.com/150',
    product_url: 'https://via.placeholder.com/150',
  },
  {
    campaign_id: '30',
    campaign_name: 'Fitness Wearables',
    description: 'Track your workouts with our latest fitness watch.',
    campaign_status: 'pending_approval',
    number_of_creators_wanted: 10,
    number_of_videos_wanted: 20,
    category: UtilsCampaignCategory.CampaignCategorySoftware,
    content_type: 'video',
    video_format: 'mp4',
    video_duration_in_seconds: 60,
    created_at: '2024-11-15T00:00:00Z',
    updated_at: '2024-11-30T00:00:00Z',
    brand_accepted: false,
    applications: [],
    creators: [],
    product_image_url: 'https://via.placeholder.com/150',
    product_url: 'https://via.placeholder.com/150',
  },
  {
    campaign_id: '31',
    campaign_name: 'Home Workout Gear',
    description: 'Effective home workouts using our resistance bands.',
    campaign_status: 'running',
    number_of_creators_wanted: 8,
    number_of_videos_wanted: 16,
    category: UtilsCampaignCategory.CampaignCategoryHealthFood,
    content_type: 'video',
    video_format: 'mp4',
    video_duration_in_seconds: 45,
    created_at: '2024-05-15T00:00:00Z',
    updated_at: '2024-12-19T00:00:00Z',
    brand_accepted: true,
    applications: [
      {
        first_name: 'Xavier',
        last_name: 'Bailey',
        avatar: 'https://i.pravatar.cc/150?img=72',
      },
    ],
    creators: [
      {
        first_name: 'Xavier',
        last_name: 'Bailey',
        avatar: 'https://i.pravatar.cc/150?img=72',
      },
    ],
    product_image_url: 'https://via.placeholder.com/150',
    product_url: 'https://via.placeholder.com/150',
  },
  {
    campaign_id: '32',
    campaign_name: 'Summer Skincare Essentials',
    description: 'Must-have skincare products for the summer heat.',
    campaign_status: 'created',
    number_of_creators_wanted: 12,
    number_of_videos_wanted: 24,
    category: 'beauty',
    content_type: 'video',
    video_format: 'mp4',
    video_duration_in_seconds: 30,
    created_at: '2024-12-15T00:00:00Z',
    updated_at: '2024-12-15T00:00:00Z',
    brand_accepted: false,
    applications: [],
    creators: [],
    product_image_url: 'https://via.placeholder.com/150',
    product_url: 'https://via.placeholder.com/150',
  },
];
