name: build and deploy

on:
  push:
    branches:
    - main
    - develop
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-1
  AWS_IAM_ROLE_ARN: arn:aws:iam::719837702058:role/github-pipeline

jobs:
  build-dev:
    if: github.ref_name == 'develop'
    runs-on: ubuntu-latest
    steps:
    - name: Get AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        audience: sts.amazonaws.com
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: ${{ env.AWS_IAM_ROLE_ARN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4
    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Get repository name
      id: repo-name
      run: |
        echo "repo-name=thrypes-se/$(echo $GITHUB_REPOSITORY | cut -f2 -d/)" >> "$GITHUB_OUTPUT"
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/${{ steps.repo-name.outputs.repo-name }}:dev-${{ github.sha }}

  deploy-dev:
    if: github.ref_name == 'develop'
    needs: build-dev
    runs-on: ubuntu-latest
    steps:
    - name: Get AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        audience: sts.amazonaws.com
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: ${{ env.AWS_IAM_ROLE_ARN }}
    - uses: actions/checkout@v4
    - uses: dkershner6/aws-ssm-getparameters-action@7d9b886c53d80ccd3c56fae27e5855e3be91aab4
      with:
        parameterPairs: |
          infra-github-terraform-modules-ssh-key = TF_MODULE_GIT_SSH_KEY
    - uses: webfactory/ssh-agent@a6f90b1f127823b31d4d4a8d96047790581349bd
      with:
        ssh-private-key: ${{ env.TF_MODULE_GIT_SSH_KEY }}
    - uses: hashicorp/setup-terraform@v3
    - name: Terraform Apply
      id: tf-apply
      working-directory: terraform/dev
      run: |
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        terraform init
        terraform apply -no-color -auto-approve -var 'service_version=dev-${{ github.sha }}'

  build-live:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
    - name: Get AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        audience: sts.amazonaws.com
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: ${{ env.AWS_IAM_ROLE_ARN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4
    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Get repository name
      id: repo-name
      run: |
        echo "repo-name=thrypes-se/$(echo $GITHUB_REPOSITORY | cut -f2 -d/)" >> "$GITHUB_OUTPUT"
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        build-args: |
          ENVIRONMENT=live
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/${{ steps.repo-name.outputs.repo-name }}:live-${{ github.sha }}

  deploy-live:
    if: github.ref_name == 'main'
    needs: build-live
    runs-on: ubuntu-latest
    steps:
    - name: Get AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        audience: sts.amazonaws.com
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: ${{ env.AWS_IAM_ROLE_ARN }}
    - uses: actions/checkout@v4
    - uses: dkershner6/aws-ssm-getparameters-action@7d9b886c53d80ccd3c56fae27e5855e3be91aab4
      with:
        parameterPairs: |
          infra-github-terraform-modules-ssh-key = TF_MODULE_GIT_SSH_KEY
    - uses: webfactory/ssh-agent@a6f90b1f127823b31d4d4a8d96047790581349bd
      with:
        ssh-private-key: ${{ env.TF_MODULE_GIT_SSH_KEY }}
    - uses: hashicorp/setup-terraform@v3
    - name: Terraform Apply
      id: tf-apply
      working-directory: terraform/live
      run: |
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        terraform init
        terraform apply -no-color -auto-approve -var 'service_version=live-${{ github.sha }}'
